### ISSUE TITLE
Redesign administrator template to Joomlatools UI

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/joomlatools-platform#319] opened 2017-05-10 13:05 UTC
Redesign the administrator template to [Joomlatools UI](https://www.joomlatools.com/developer/ui/).

## Core hacks
Core hacks, check if we can find another way around them so they can be reverted:
- https://github.com/joomlatools/joomlatools-platform/commit/a31e086bafe4491e823ed4e05c93ea776e2c86c0
- https://github.com/joomlatools/joomlatools-platform/commit/110c329ef8abf473d20a5e195d4b7746d967e788
- https://github.com/joomlatools/joomlatools-platform/commit/694373d9634c05bad96af9b5896d556031a6ee02

## Bugs:
- Some views can't sort on ordering column for drag and drop ordering. For example see plugins view
- Find `@TODO` in the code for all other bugs

## Testing:
- RTL testing

## Improvements:
- Add better dropdown script (checking wether to drop to: `top`, `right`, `bottom` or `left`)
- Let filters display current setting
- Let filters show how many are active on mobile (the red dot)
- Create a small toggle button for the toolbar so you get to see all labels on mobile instead of just icons?
- Do not show toolbar when it's empty (debug users for example)
- Group fields in item views using form-block styling? (see menu items)

## Features:
- Add handy quicklinks etc. to sidebars
- Analytics / imgix etc. dashboard items?
- MCE editor from TEXTman as editor? / TEXTman as default editor?
- Put whole UI in 8 pixel grid (should be done in Kodekit UI)
- Onboarding on all views

## To KUI:
- Autofocus (select2 open) first item in filter dropdown for faster selection
- Bounce scroll edges iOs (utilities/setup.scss) to CSS

**Comment by robinpoort** [comment] 2017-07-24 12:56
@johanjanssens I think I've got a first version ready for deployment. There's a few small bugs and improvements (see ticket description) but they are not big enough to delay a first release of the new template.

Could you test the template and see if everything feels good for our clients? You (and maybe more Timblians) can create tickets for me to pick up after my holiday.

The next step would be to finish / polish this and then improve on it on the Scicasts repo. There are more components in Scicasts so that'll be a good testing ground to further improve on the template.

**Comment by johanjanssens** [comment] 2017-07-24 12:58
@robinpoort Excellent! We will start the testing process. Enjoy the holidays, tickets will be waiting afterwards.

**Comment by johanjanssens** [comment] 2017-07-24 13:00
@raeldc @allanpilarca Can you guys test the work done by Robin in this branch. See what possible issues you find, so far only the core platform has been styled, we haven't added styling for other components yet.

**Comment by allanpilarca** [comment] 2017-07-26 08:18
@robinpoort @johanjanssens compiled and added the issues found in  the google docs https://drive.google.com/open?id=1eXPCSUSqp4R9_plNWpHttREQDzPydLyzpJCGeUEaZTw

Noticed that the issue regarding move-icon for sorting is already in the description but i also just include it in the docs.

**Comment by robinpoort** [comment] 2017-08-21 14:52
@allanpilarca Thanks for testing. I added some notes to the doc. Can you re-test the  things I fixed?

As for the remaining bugs:
1. The ordering issue I'm not sure how to fix
2. The custom module position in the default template is probably done by adding extra JS to the chosen selectbox. Since we're using select2 now this code is not working anymore. We should find a proper solution for this.
3. Can you recall when and where you got the notices? Would be really helpful to fix them :)

**Comment by allanpilarca** [comment] 2017-08-22 08:56
Hi @robinpoort made another testing and i can confirmed that your fix are all working. :)

1. Noticed that the ordering in menu items page are working, might be just a markup issue. If not then could also be related here https://github.com/joomlatools/joomlatools-platform/issues/287

2. Agree, we need to find a proper solution for this.

3. These are the pages where i see the notices:

Menu Items View: http://joomla.box/joomlatools-platform/web/administrator/index.php?option=com_menus&view=items

![screen shot 2017-08-22 at 4 20 35 pm](https://user-images.githubusercontent.com/194313/29555858-89635556-8756-11e7-9896-0e66bb303c83.jpg)

Plugins View: http://joomla.box/joomlatools-platform/web/administrator/index.php?option=com_plugins

![screen shot 2017-08-22 at 4 21 00 pm](https://user-images.githubusercontent.com/194313/29555864-8eef1c58-8756-11e7-97ac-8cb0fec8bccb.jpg)

**Comment by robinpoort** [comment] 2017-08-22 09:36
@allanpilarca I'm not seeing the errors but I've pushed two potential fixes. Could you check if the errors are now gone?

As for `2.`, I'll try and come up with a solution

**Comment by robinpoort** [comment] 2017-08-22 11:19
@allanpilarca Came up with a rather simple solution already built-in select2. Can you give it a quick test?

**Comment by robinpoort** [comment] 2017-08-22 14:06
@allanpilarca Also added a fix for the ordering. And improved the top menu (hovering to other items while the first one is opened is now supported)

**Comment by allanpilarca** [comment] 2017-08-23 02:44
@robinpoort there are only 2 notices displaying in menu items page. The $assoc and $prefix variable. You can see the errors by setting in your box to display all the errors. 
`box php:ini error_reporting E_ALL`

The fix in sorting and custom module position is now working. Nice work sir! :)

**Comment by robinpoort** [comment] 2017-08-23 09:59
@allanpilarca They should be gone as well now :)

**Comment by allanpilarca** [comment] 2018-01-29 02:59
hi @robinpoort 

Does this ticket only support design/layouts for joomlatools-platform core? or does this also need to support the design/layouts for com:content and other joomlatools-platform extensions? I tried checking com:content and found some styling that still needs to style.

**Comment by robinpoort** [comment] 2018-01-29 12:47
@allanpilarca I think we put styling for other components on pause for the moment. We'll have to wait and see what @johanjanssens thinks of this. As far as I know, other components have not been fully styled yet. So if they need to be, it'll take some additional work.

**Comment by johanjanssens** [comment] 2018-02-07 22:11
This is a betwixed and between situation right now, we want to use the template for scicasts, but they are still using com_content in the admin, at the same time we are trying to move them completely into the frontend using TEXTman.

@robinpoort  How much effort would there to make the template work with com_content in admin?

**Comment by robinpoort** [comment] 2018-02-09 09:23
@johanjanssens Probably a day or so with testing if we're only talking about the list and form view for com_content. But I might run into problems so it might also be a few days..

**Comment by johanjanssens** [comment] 2018-02-21 23:34
@robinpoort Can you give this a go then? Would be nice if we can wrap up this work. Spend quite some time into this already.

**Comment by robinpoort** [comment] 2018-03-01 14:03
@johanjanssens @allanpilarca 

Another big round of improvements!
- Added Kodekit UI v1.0.0
- Added styling for com_content, com_categories and com_tags
- Improved styling for several other components
- Improvements in form fields for several views
- Fixed as much @TODOs as possible
- Small mobile view improvements

I am not very sure about if the following files are being used:

- web/administrator/templates/elysio/html/com_categories/categories/modal.php
- web/administrator/templates/elysio/html/com_categories/category/modal.php
- web/administrator/templates/elysio/html/com_categories/category/modal_options.php
- web/administrator/templates/elysio/html/com_menus/items/default_batch_body.php
- web/administrator/templates/elysio/html/com_menus/items/default_batch_footer.php
- web/administrator/templates/elysio/html/com_modules/modules/modal.php

Ofcourse these can be removed and everything still works because they are overrides. So I'm actually wondering if these files are being used:

- app/administrator/components/com_categories/views/categories/tmpl/modal.php
- app/administrator/components/com_categories/views/category/tmpl/modal.php
- app/administrator/components/com_categories/views/category/tmpl/modal_options.php
- app/administrator/components/com_menus/views/items/tmpl/default_batch_body.php
- app/administrator/components/com_menus/views/items/tmpl/default_batch_footer.php
- app/administrator/components/com_modules/views/modules/tmpl/modal.php

If they are being used, can one of you let me know how I'm able to view them inside the administrator? Which links should I click to get those views? It's impossible for me to style them otherwise :)

Other than those views, can you test and see if everything works as expected? Thanks!

**Comment by johanjanssens** [comment] 2018-03-01 22:47
@robinpoort I think these modal views are used for the batch modal in categories, menus and modules? Could that be?

**Comment by johanjanssens** [comment] 2018-03-01 22:48
@allanpilarca Can you do testing?

**Comment by allanpilarca** [comment] 2018-03-02 07:58
hi @robinpoort 

Nice work with the template :) found some small issues:

1. The modal displayed when clicking the "Created by" field in article form in publishing tab.(This happens in every "Created by" field) - https://joomlatools-platform.dev/administrator/index.php?option=com_content&view=article&layout=edit

![screen shot 2018-03-02 at 1 36 01 pm](https://user-images.githubusercontent.com/194313/36888817-2f25ad96-1e32-11e8-9936-4a5dcb49a1d9.jpg)

2. Found this Notice : Undefined property: TagsViewTags::$sidebar in /var/www/joomlatools-platform/web/administrator/templates/elysio/html/com_tags/tags/default.php on line 34 - https://joomlatools-platform.dev/administrator/index.php?option=com_tags

3. The "Select categories" field in "Layout" tab when creating a "Featured Articles" menu - https://joomlatools-platform.dev/administrator/index.php?option=com_menus&view=item&layout=edit

![screen shot 2018-03-02 at 2 14 04 pm](https://user-images.githubusercontent.com/194313/36888876-6298ed50-1e32-11e8-8aa3-041edd28d443.jpg)

4. Logo not displayed

![screen shot 2018-03-02 at 3 55 10 pm](https://user-images.githubusercontent.com/194313/36888891-71d19cae-1e32-11e8-9dcc-0ab40032868a.jpg)
![screen shot 2018-03-02 at 3 54 52 pm](https://user-images.githubusercontent.com/194313/36888893-734d3610-1e32-11e8-8ba6-fb41e171d69d.jpg)

I cant find an exact link that currently used this layouts in platform
- `app/administrator/components/com_categories/views/categories/tmpl/modal.php` (This is used to display a modal that will list categories and allow user to select from it)
- `app/administrator/components/com_categories/views/category/tmpl/modal.php` (In joomla 3.7.5 when creating a menu pointing to category blog view the user can select a category and allows the user to edit the category directly from this page through a modal displaying the category form.)

I think these files are not used since its code is already in `app/administrator/components/com_menus/views/items/tmpl/default_batch.php`
- `app/administrator/components/com_menus/views/items/tmpl/default_batch_body.php`
- `app/administrator/components/com_menus/views/items/tmpl/default_batch_footer.php`

This file is used in displaying a list of modules using the editor-xtd module button plugin, we didnt include it the platform so we no longer need this override
- `app/administrator/components/com_modules/views/modules/tmpl/modal.php`

**Comment by robinpoort** [comment] 2018-03-02 08:38
Hi Allan,

Thanks for testing!

1. Fixed!
2. I'm not having the error myself, any idea on how to solve the issue? Or an idea on how I can get that error as well? :)
3. Fixed! There might be more of them, if you ever encounter one let me know (or add to `web/administrator/templates/elysio/scripts/main.js:9`)
4. Can you check your "Elysio" template settings? Both fields should be empty or point to a valid logo:
![screen shot 2018-03-02 at 09 29 51](https://user-images.githubusercontent.com/4848082/36889931-556a236e-1dfc-11e8-8e3d-2da3e7017b4c.png)

- `app/administrator/components/com_categories/views/categories/tmpl/modal.php` removed this file from the template. So it will grab the Joomla default one if ever used.
- `app/administrator/components/com_categories/views/category/tmpl/modal.php` removed this since the platform is forked from Joomla 3.3
- `app/administrator/components/com_menus/views/items/tmpl/default_batch_body.php` what I thought already, removed
- `app/administrator/components/com_menus/views/items/tmpl/default_batch_footer.php` what I thought already, removed
- `app/administrator/components/com_modules/views/modules/tmpl/modal.php` removed

@allanpilarca There's some other `default_batch_body.php` and `default_batch_footer.php`files that might not be in use. The reason I didn't mention these before is because there's some extra PHP code in them and I can't be sure wether it's doing anything. But if you could check if they can be removed that'd be great!

@johanjanssens it might be wise to remove those unused files from the platform itself as well? If they're not being used they can go right?

**Comment by johanjanssens** [comment] 2018-03-02 16:34
@robinpoort whatever isn't used can be removed indeed. I think we originally took a copy of the existing template, so there might be files in there that are not needed @allanpilarca Can you double check?

**Comment by allanpilarca** [comment] 2018-03-05 09:39
@robinpoort 

2. I added some changes to fix the notification displayed. You can also check the error notification by setting this to your box `box php:ini error_reporting E_ALL`

4. I confirmed that's the reason causing not to display the logo correctly, when installing the template it includes a default value but the image does not exists. I removed it in the installation script and keep it empty.

@johanjanssens 

Upon double checking i found out that the `default_batch_body.php` and `default_batch_footer.php` files are still used in `app/administrator/components/com_menus/views/items/tmpl/default.php` [line-255]( https://github.com/joomlatools/joomlatools-platform/blob/master/app/administrator/components/com_menus/views/items/tmpl/default.php#L255-L257) but in the template override of `default.php` we used the `default_batch.php` when displaying the modal for batch updates.

So we cant remove those files because its still being used.

I also found an error when trying to do a batch operation, will create a separate ticket for it.

**Comment by johanjanssens** [comment] 2018-03-06 01:47
Thanks, good work @allanpilarca

**Comment by robinpoort** [comment] 2018-03-06 08:12
Thanks @allanpilarca ! Double-check; there's nothing I have to do for this anymore right?

**Comment by allanpilarca** [comment] 2018-03-06 08:16
@robinpoort seems the template is done. :)

**Comment by robinpoort** [comment] 2018-03-06 08:25
👍

**Comment by johanjanssens** [comment] 2018-03-06 15:30
Excellent work, @allanpilarca can you merge it and close it. One more down.

**Closed** 2018-03-07 03:29 UTC
Labels: feature
